services:
  docmost:
    container_name: docmost
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: '${APP_SECRET}'
      DATABASE_URL: 'postgresql://docmost:${DOCMOST_URL}@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      TZ: Asia/Phnom_Penh
    networks:
      - docmost
    ports:
      - "2010:3000"
    restart: unless-stopped
    volumes:
      - /mnt/emmc/docmost/docmost:/app/data/storage
  db:
    container_name: docmost-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${POSTGRES_DB}
      TZ: Asia/Phnom_Penh
    restart: unless-stopped
    networks:
      - docmost
    volumes:
      - /mnt/emmc/docmost/docmost_db:/var/lib/postgresql/data

  redis:
    container_name: docmost-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - docmost
    volumes:
      - /mnt/emmc/docmost/docmost_redis:/data

networks:
  docmost:
    external: true
